// MIX Engine — IDE type declarations
// Generated by CommandRegistry — do not edit manually.

declare namespace MixEngine {

  interface ScriptAPI {
    entityId: number;
    readonly position: import('three').Vector3 | undefined;
    readonly rotation: import('three').Quaternion | undefined;
    events: ScriptEvent[];
    state: PersistentStateAPI;
    debug: DebugDrawAPI;
  }

  interface ScriptEvent {
    type: 'sensor';
    otherEntityId: number;
    intersecting: boolean;
  }

  interface PersistentStateAPI {
    getItem: <T = unknown>(key: string) => T | undefined;
    setItem: (key: string, value: unknown) => void;
    removeItem: (key: string) => void;
    clear: () => void;
    getAll: () => Record<string, unknown>;
  }

  interface DebugDrawAPI {
    drawLine(from: import('three').Vector3, to: import('three').Vector3, color?: number | string, lifetime?: number): void;
    drawRay(origin: import('three').Vector3, direction: import('three').Vector3, length: number, color?: number | string, lifetime?: number): void;
    drawBox(center: import('three').Vector3, size: import('three').Vector3, color?: number | string, lifetime?: number): void;
    drawSphere(center: import('three').Vector3, radius: number, color?: number | string, lifetime?: number): void;
    drawText(position: import('three').Vector3, text: string, color?: number | string, size?: number, lifetime?: number): void;
    clearAll(): void;
  }

  type AudioBus = 'music' | 'sfx' | 'ambient' | 'voice';
  type InputMode = 'editor' | 'character' | 'vehicle' | 'cinematic';
  type NavAgentMode = 'idle' | 'wander' | 'seek' | 'flee' | 'pursue' | 'evade' | 'pathfollow' | 'patrol' | 'behavior_tree' | 'queue';
  type VfxPresetName = string;
  type AssetType = string;
  type DamageType = string;
  type ScenarioProfile = string;

  interface EntityBlueprint { kind: string; params: Record<string, unknown> }
  interface SteeringParams { maxSpeed?: number; maxForce?: number; arriveRadius?: number; wanderJitter?: number; wanderRadius?: number; wanderDistance?: number; separationRadius?: number; separationWeight?: number; alignmentWeight?: number; cohesionWeight?: number; obstacleAvoidanceRadius?: number; obstacleAvoidanceWeight?: number; }
  interface WheelSpecInput { attach: [number, number, number]; suspensionRestLength?: number; springStiffness?: number; springDamping?: number; radius: number; maxTravel?: number; lateralFriction?: number; longitudinalFriction?: number; driven?: boolean; steered?: boolean; }

  type AICommand =
    | { type: 'ability_cast'; slot?: number }
    | { type: 'active_ragdoll_attach'; entityId: number | string | Record<string, any>; muscleStiffness?: any; muscleDamping?: any; strength?: number }
    | { type: 'active_ragdoll_knockdown'; entityId: number | string | Record<string, any>; seconds?: any }
    | { type: 'active_ragdoll_strength'; entityId: number | string | Record<string, any>; strength: number }
    | { type: 'add_light'; kind: string; position: Record<string, any>; color?: string; intensity?: number; distance?: number; castShadow?: boolean; target?: string; angle?: number; penumbra?: number; decay?: number; width?: number; height?: number; cookie?: any }
    | { type: 'add_nav_agent'; entityId: number | string | Record<string, any>; mode?: string; targetX?: any; targetY?: any; targetZ?: any; targetEntityId?: number | string | Record<string, any>; patrol?: any; patrolLoop?: any; steering?: Record<string, any>; behaviorTree?: any; faceMovement?: any; groundSnap?: any; tag?: string; flockRadius?: any; queueLaneWidth?: any }
    | { type: 'add_script'; entityId: number | string | Record<string, any>; sourceCode: string }
    | { type: 'add_trigger_zone'; id: string; x: number; y: number; z: number; radius: number; enterSound?: any; exitSound?: any; ambientSound?: any; volume?: number }
    | { type: 'add_vehicle'; entityId: number | string | Record<string, any>; wheels: any[]; spec?: Record<string, any> }
    | { type: 'anim_event_add'; state: string; normalizedTime: any; event: string; payload?: any }
    | { type: 'anim_pack_apply'; packId: string; target?: string; prefix?: any }
    | { type: 'anim_pack_list' }
    | { type: 'anim_pack_preview'; packId: string; entryId: any; entityId?: number | string | Record<string, any>; fade?: number }
    | { type: 'anim_pack_remove'; packId: string }
    | { type: 'anim_pack_wire_combat'; packId: string; mapping?: any; auto?: any; target?: string; prefix?: any }
    | { type: 'apply_impulse'; entityId: number | string | Record<string, any>; x: number; y: number; z: number }
    | { type: 'arena_launch_demo' }
    | { type: 'arena_start' }
    | { type: 'attach_sound'; entityId: number | string | Record<string, any>; src: string; volume?: number; loop?: boolean }
    | { type: 'bake_ao'; samples?: any; distance?: number; strength?: number; seed?: number }
    | { type: 'bake_apply'; name: string }
    | { type: 'bake_flush' }
    | { type: 'bake_list' }
    | { type: 'bake_scene'; name?: string }
    | { type: 'buoyancy_add'; entityId: number | string | Record<string, any>; volume?: number; height?: number }
    | { type: 'buoyancy_remove'; entityId: number | string | Record<string, any> }
    | { type: 'buoyancy_status'; entityId: number | string | Record<string, any> }
    | { type: 'burst_vfx'; preset: string; x: number; y: number; z: number; count?: number }
    | { type: 'camera_preset'; preset: string; anchorToSelection?: boolean }
    | { type: 'camera_preset_next' }
    | { type: 'camera_preset_prev' }
    | { type: 'camera_shake'; trauma?: any; duration?: number; frequency?: number; translation?: any; rotation?: Record<string, any> }
    | { type: 'character_motion_setup'; entityId: number | string | Record<string, any>; packId?: string }
    | { type: 'chunk_deltas_clear' }
    | { type: 'chunk_deltas_export' }
    | { type: 'chunk_deltas_import'; data: any }
    | { type: 'cinematic_play'; sequence: Record<string, any> }
    | { type: 'cinematic_stop' }
    | { type: 'clear_debug_draw' }
    | { type: 'clear_scene' }
    | { type: 'clear_state' }
    | { type: 'cloth_create_grid'; id: string; width: number; height: number; segsX: any; segsY: any; pinTop?: boolean }
    | { type: 'cloth_list' }
    | { type: 'cloth_remove'; id: string }
    | { type: 'clouds_set'; enabled?: boolean; coverage?: any; density?: any; speed?: number; scale?: number; heightBottom?: number; heightTop?: number; color?: string }
    | { type: 'collision_layer_define'; name: string; id?: string; collidesWith: any[] }
    | { type: 'collision_matrix_get' }
    | { type: 'collision_set_layer'; entityId: number | string | Record<string, any>; layer: string }
    | { type: 'combat_add_health'; entityId: number | string | Record<string, any>; hp: number; faction?: any; damageMultiplier?: number }
    | { type: 'combat_add_hitbox'; entityId: number | string | Record<string, any>; colliderHandle: any; part: any; multiplier?: number }
    | { type: 'combat_apply_damage'; attackerId?: number | string | Record<string, any>; targetId: number | string | Record<string, any>; amount: number; damageType?: any }
    | { type: 'combat_equip_weapon'; entityId: number | string | Record<string, any>; weapon: any }
    | { type: 'combat_fire'; entityId: number | string | Record<string, any>; originX: any; originY: any; originZ: any; dirX: number; dirY: any; dirZ: number }
    | { type: 'combat_motion_setup'; entityId: number | string | Record<string, any>; packId?: string }
    | { type: 'combat_status' }
    | { type: 'component_add'; entityId: number | string | Record<string, any>; component: string; props?: Record<string, any> }
    | { type: 'component_get'; entityId: number | string | Record<string, any>; component: string }
    | { type: 'component_remove'; entityId: number | string | Record<string, any>; component: string }
    | { type: 'component_set'; entityId: number | string | Record<string, any>; component: string; prop: string; value: any }
    | { type: 'components_list' }
    | { type: 'crossfade_music'; src: string; duration?: number }
    | { type: 'cull_enable'; enabled: boolean; occlusion?: boolean; hierarchicalFrustum?: boolean }
    | { type: 'cull_rebuild' }
    | { type: 'cull_set_exclude'; entityId: number | string | Record<string, any>; exclude: any }
    | { type: 'cull_set_occluder'; entityId: number | string | Record<string, any>; occluder: any }
    | { type: 'cull_status' }
    | { type: 'cutscene_play'; sequence: Record<string, any> }
    | { type: 'cutscene_stop' }
    | { type: 'cutscene_subtitle'; text: string; speaker?: string; duration?: number }
    | { type: 'day_night_cycle'; enabled?: boolean; hour?: number; speed?: number }
    | { type: 'decal_spawn'; position: Record<string, any>; normal: Record<string, any>; size?: any; color?: string; lifespan?: any }
    | { type: 'delete_save'; slot: string }
    | { type: 'destroy_entity'; entityId: number | string | Record<string, any> }
    | { type: 'dialogue_show'; text: string; speaker?: string; choices?: any; pauseGame?: boolean }
    | { type: 'director_set_phase'; phase: any }
    | { type: 'draw_debug_box'; centerX: any; centerY: any; centerZ: any; sizeX: any; sizeY: any; sizeZ: any; color?: string; lifetime?: any }
    | { type: 'draw_debug_line'; fromX: number; fromY: number; fromZ: number; toX: number; toY: number; toZ: number; color?: string; lifetime?: any }
    | { type: 'draw_debug_ray'; originX: any; originY: any; originZ: any; dirX: number; dirY: any; dirZ: number; length: any; color?: string; lifetime?: any }
    | { type: 'draw_debug_sphere'; centerX: any; centerY: any; centerZ: any; radius: number; color?: string; lifetime?: any }
    | { type: 'draw_debug_text'; x: number; y: number; z: number; text: string; color?: string; size?: any; lifetime?: any }
    | { type: 'emit_event'; event: string; data?: any }
    | { type: 'eqs_query'; querier: any; target?: string; generator: Record<string, any>; tests: any }
    | { type: 'explosion_feedback'; x?: number; y?: number; z?: number; color?: string }
    | { type: 'export_tauri_manifest'; title?: string; version?: string; fullscreen?: any }
    | { type: 'export_typings' }
    | { type: 'feature_apply_preset'; preset?: string }
    | { type: 'feature_configure'; feature?: string; config?: Record<string, any> }
    | { type: 'feature_disable'; feature?: string }
    | { type: 'feature_enable'; feature?: string }
    | { type: 'feature_enable_all' }
    | { type: 'feature_list' }
    | { type: 'find_path'; fromX: number; fromY: number; fromZ: number; toX: number; toY: number; toZ: number; smooth?: boolean; goalTolerance?: any }
    | { type: 'focus_entity'; entityId: number | string | Record<string, any> }
    | { type: 'fog_set_params'; density?: any; heightFalloff?: any; groundLevel?: any; color?: string; anisotropy?: any }
    | { type: 'fog_volume_add'; id: string; position: Record<string, any>; radius: number; density: any; color?: string }
    | { type: 'foliage_clear' }
    | { type: 'foliage_populate'; entityId?: number | string | Record<string, any>; density?: any; radius?: number; seed?: number }
    | { type: 'foliage_set'; enabled?: boolean; density?: any }
    | { type: 'follow_path'; entityId: number | string | Record<string, any>; points: any[]; speed?: number; loop?: boolean; lookAlongPath?: boolean }
    | { type: 'foot_ik_set'; entityId: number | string | Record<string, any>; enabled: boolean; rayLength?: any; footOffset?: any; maxPelvisDrop?: any; smoothSpeed?: any }
    | { type: 'frame_all'; padding?: any }
    | { type: 'frame_entity'; entityId: number | string | Record<string, any>; padding?: any }
    | { type: 'game_essentials_status' }
    | { type: 'game_notify'; message?: string }
    | { type: 'game_pause' }
    | { type: 'game_resume' }
    | { type: 'game_settings_set'; settings?: Record<string, any> }
    | { type: 'gameplay_advance'; quest: string; objective: string; by?: any }
    | { type: 'gameplay_complete_quest'; quest: string }
    | { type: 'gameplay_dialogue_choose'; index: number }
    | { type: 'gameplay_dialogue_start'; id: string }
    | { type: 'gameplay_fail_quest'; quest: string }
    | { type: 'gameplay_load'; def: Record<string, any> }
    | { type: 'gameplay_reset' }
    | { type: 'gameplay_set_var'; key: string; value: any }
    | { type: 'gameplay_signal'; name: string; data?: any }
    | { type: 'gameplay_start_quest'; quest: string }
    | { type: 'gameplay_status' }
    | { type: 'get_state'; key: string }
    | { type: 'goap_plan'; startState: any; goalState: any; actions: any[] }
    | { type: 'gpu_particles_start'; maxParticles?: any; x?: number; y?: number; z?: number }
    | { type: 'gpu_particles_status' }
    | { type: 'gpu_particles_stop' }
    | { type: 'history_clear' }
    | { type: 'history_list' }
    | { type: 'hit_feedback'; x?: number; y?: number; z?: number; color?: string; intensity?: number; vfx?: any }
    | { type: 'hlod_create'; id: string; entityIds: any[]; prototypeEntityId?: number | string | Record<string, any>; nearDistance?: any; farDistance?: any; views?: any; tileSize?: any }
    | { type: 'hlod_list' }
    | { type: 'hlod_remove'; id: string }
    | { type: 'hud_clear' }
    | { type: 'hud_hide'; id: string }
    | { type: 'hud_load'; layout: Record<string, any> }
    | { type: 'hud_show'; id: string }
    | { type: 'ik_aim_target'; entityId: number | string | Record<string, any>; target: string; weight?: number }
    | { type: 'import_animation_pack'; packId: string; targetRig: any; sourcePath?: any; displayName?: any; boneMappingOverride?: any; scaleOverride?: any; keepRootMotion?: any; qualityPreset?: any; footLock?: any }
    | { type: 'import_asset'; id: string; url: string; assetType?: any }
    | { type: 'import_clear'; id?: string }
    | { type: 'import_list' }
    | { type: 'input_action_define'; name: string; kind: string; bindings?: any; deadzone?: any; responseCurve?: any; context?: any }
    | { type: 'input_action_state'; action: string }
    | { type: 'input_actions' }
    | { type: 'input_bind'; action: string; binding: Record<string, any> }
    | { type: 'input_context_pop'; name?: string }
    | { type: 'input_context_push'; name: string; priority?: any; actions?: any[]; maskAllBelow?: boolean }
    | { type: 'input_contexts' }
    | { type: 'input_gamepad_controls' }
    | { type: 'input_gamepad_rumble'; pad?: any; durationMs?: number; weakMagnitude?: number; strongMagnitude?: number }
    | { type: 'input_gamepad_status' }
    | { type: 'input_remap'; actions: any[]; context?: any }
    | { type: 'input_synthetic'; action: string; value: any }
    | { type: 'input_unbind'; action: string }
    | { type: 'inspect_deserialize'; json: any }
    | { type: 'inspect_diff'; a: any; b: any }
    | { type: 'inspect_property_get'; entityId: number | string | Record<string, any>; path: string }
    | { type: 'inspect_property_set'; entityId: number | string | Record<string, any>; path: string; value: any }
    | { type: 'inspect_schema_define'; target: string; schema: Record<string, any> }
    | { type: 'inspect_schema_get'; target: string }
    | { type: 'inspect_schema_patch'; target: string; patch: Record<string, any> }
    | { type: 'inspect_serialize'; entityId: number | string | Record<string, any> }
    | { type: 'inspect_validate'; entityId?: number | string | Record<string, any>; scope?: any; dryRun?: boolean; autoFix?: boolean }
    | { type: 'interaction_register'; def: Record<string, any> }
    | { type: 'interaction_set_enabled'; id: string; enabled: boolean }
    | { type: 'interaction_status' }
    | { type: 'interaction_trigger'; id: string }
    | { type: 'interaction_unregister'; id: string }
    | { type: 'inventory_clear'; owner?: any }
    | { type: 'inventory_give'; item: string; count?: number; owner?: any }
    | { type: 'inventory_list'; owner?: any }
    | { type: 'inventory_remove'; item: string; count?: number; owner?: any }
    | { type: 'inventory_transfer'; from: string; to: string; item: string; count?: number }
    | { type: 'inventory_use'; item: string; owner?: any }
    | { type: 'item_define'; def: Record<string, any> }
    | { type: 'joint_create'; jointType: string; entityA: any; entityB: any; anchorA: Record<string, any>; anchorB: Record<string, any>; axisA?: Record<string, any>; axisB?: Record<string, any>; limits?: Record<string, any>; motor?: Record<string, any>; breakForce?: number }
    | { type: 'joint_remove'; jointId: string }
    | { type: 'joints_list' }
    | { type: 'kcc_get_params'; entityId: number | string | Record<string, any> }
    | { type: 'kcc_get_state'; entityId: number | string | Record<string, any> }
    | { type: 'kcc_get_telemetry'; entityId: number | string | Record<string, any> }
    | { type: 'kcc_set_params'; entityId: number | string | Record<string, any>; params: Record<string, any> }
    | { type: 'kcc_telemetry_get'; entityId: number | string | Record<string, any> }
    | { type: 'kcc_teleport'; entityId: number | string | Record<string, any>; x: number; y: number; z: number }
    | { type: 'list_camera_presets' }
    | { type: 'list_saves' }
    | { type: 'list_state' }
    | { type: 'load_game'; slot: string }
    | { type: 'load_scene'; name?: string }
    | { type: 'load_state_snapshot'; name: string }
    | { type: 'locomotion_motion_setup'; entityId: number | string | Record<string, any>; mode?: string }
    | { type: 'lod_enable'; enabled: boolean }
    | { type: 'lod_register'; entityId: number | string | Record<string, any>; distances?: any[]; ratios?: any[] }
    | { type: 'lod_unregister'; entityId: number | string | Record<string, any> }
    | { type: 'mesh_fracture'; entityId: number | string | Record<string, any>; epicenter?: any; pieces?: any; impulse?: any; lifespan?: any }
    | { type: 'morph_get'; entityId: number | string | Record<string, any>; morph: any }
    | { type: 'morph_set'; entityId: number | string | Record<string, any>; morph: any; weight: number; duration?: number }
    | { type: 'morph_set_weight'; entityId: number | string | Record<string, any>; morph: any; weight: number; duration?: number }
    | { type: 'morphs_list'; entityId: number | string | Record<string, any> }
    | { type: 'motion_crossfade'; entityId: number | string | Record<string, any>; targetClip: any; fade?: number; layer?: string }
    | { type: 'motion_graph_inspect'; entityId: number | string | Record<string, any>; include?: any }
    | { type: 'motion_layer_create'; entityId: number | string | Record<string, any>; name: string; index?: number; blendMode?: any; mask?: any }
    | { type: 'motion_layer_weight'; entityId: number | string | Record<string, any>; layer: string; weight: number; fade?: number }
    | { type: 'motion_parameter_get'; entityId: number | string | Record<string, any>; name: string }
    | { type: 'motion_parameter_set'; entityId: number | string | Record<string, any>; name: string; value: any; damping?: number }
    | { type: 'motion_pause'; entityId: number | string | Record<string, any> }
    | { type: 'motion_play'; entityId: number | string | Record<string, any>; clip: string; packId?: string; layer?: string; fade?: number; speed?: number; loop?: boolean; rootMotion?: any }
    | { type: 'motion_preview'; clip: string; packId?: string; entityId?: number | string | Record<string, any>; fade?: number }
    | { type: 'motion_quality_report'; entityId: number | string | Record<string, any> }
    | { type: 'motion_resume'; entityId: number | string | Record<string, any> }
    | { type: 'motion_stop'; entityId: number | string | Record<string, any>; fade?: number; layer?: string }
    | { type: 'nav_debug'; enabled?: boolean }
    | { type: 'nav_goto'; entityId: number | string | Record<string, any>; target: string; pathMode?: any; arriveRadius?: any; requirePath?: any; timeoutSec?: any }
    | { type: 'nav_query'; x: number; z: number }
    | { type: 'nav_register_landmark'; name: string; x: number; y: number; z: number; radius?: number }
    | { type: 'navmesh_auto'; enabled: boolean; maxRegionsPerFrame?: any; maxQueued?: any }
    | { type: 'navmesh_build'; centerX: any; centerZ: any; size: any; cellSize?: number; agentRadius?: number; agentHeight?: number; maxSlopeDeg?: number; maxStepHeight?: number }
    | { type: 'navmesh_build_multilayer'; centerX: any; centerZ: any; size: any; cellSize?: number; agentRadius?: number; agentHeight?: number; maxSlopeDeg?: number; maxStepHeight?: number }
    | { type: 'navmesh_invalidate'; minX: number; minZ: number; maxX: number; maxZ: number }
    | { type: 'network_disconnect' }
    | { type: 'network_host'; url: string }
    | { type: 'network_join'; url: string }
    | { type: 'network_local_player'; entityId: number | string | Record<string, any> }
    | { type: 'network_replicate'; entityId: number | string | Record<string, any>; enabled?: boolean }
    | { type: 'network_status' }
    | { type: 'objective_add'; id?: string; title?: string; target?: number }
    | { type: 'objective_advance'; id?: string; amount?: number }
    | { type: 'package_game'; title?: string; entryScene?: any; visualStyle?: any }
    | { type: 'parent_entity'; entityId: number | string | Record<string, any>; parentId: number | string | Record<string, any> }
    | { type: 'play_animation'; entityId: number | string | Record<string, any>; state: string; fade?: number }
    | { type: 'play_sound'; src: string; x?: number; y?: number; z?: number; volume?: number; loop?: boolean; refDistance?: any; maxDistance?: any }
    | { type: 'playback_run'; script: any }
    | { type: 'playback_status' }
    | { type: 'playback_stop' }
    | { type: 'prefab_instances' }
    | { type: 'prefab_list' }
    | { type: 'prefab_register'; prefab: any }
    | { type: 'prefab_spawn'; name: string; position: Record<string, any>; rotation?: Record<string, any>; variant?: any }
    | { type: 'prefab_unpack'; rootEntity: any }
    | { type: 'preload_assets'; ids: any[] }
    | { type: 'profiler_clear' }
    | { type: 'profiler_history'; limit?: number }
    | { type: 'profiler_set'; enabled: boolean }
    | { type: 'profiler_status' }
    | { type: 'query_raycast'; origin: Record<string, any>; direction: Record<string, any>; maxDistance?: any }
    | { type: 'query_scene'; filter?: Record<string, any> }
    | { type: 'query_sphere'; center: Record<string, any>; radius: number; tags?: any[] }
    | { type: 'ragdoll_create'; rootEntity: any; x?: number; y?: number; z?: number }
    | { type: 'ragdoll_destroy'; rootEntity: any }
    | { type: 'ragdoll_set_active'; rootEntity: any; active: boolean }
    | { type: 'ragdoll_set_dynamic'; rootEntity: any; dynamic: boolean }
    | { type: 'ragdoll_spawn'; rootEntity: any; x?: number; y?: number; z?: number }
    | { type: 'redo' }
    | { type: 'reflection_probe_capture'; probeId: string }
    | { type: 'reflection_probe_create'; probeId: string; position: Record<string, any>; resolution?: any; boxSize?: any; intensity?: number }
    | { type: 'reflection_probe_remove'; probeId: string }
    | { type: 'register_asset'; id: string; path: string; assetType?: any }
    | { type: 'remove_nav_agent'; entityId: number | string | Record<string, any> }
    | { type: 'remove_script'; entityId: number | string | Record<string, any> }
    | { type: 'remove_state'; key: string }
    | { type: 'remove_tag'; entityId: number | string | Record<string, any>; tag: string }
    | { type: 'remove_trigger_zone'; id: string }
    | { type: 'remove_vehicle'; entityId: number | string | Record<string, any> }
    | { type: 'replay_pause' }
    | { type: 'replay_play' }
    | { type: 'replay_set_frame'; frame: number }
    | { type: 'replay_start_recording' }
    | { type: 'replay_step' }
    | { type: 'replay_step_back' }
    | { type: 'replay_stop' }
    | { type: 'replay_stop_recording' }
    | { type: 'retarget_pro_build'; packId: string; targetRig: any; sourcePath: any; displayName?: any; qualityPreset?: any; strict?: boolean; target?: string; autoApply?: boolean; autoWireCombat?: boolean; previewEntry?: any; prefix?: any; keepRootMotion?: any; boneMappingOverride?: any; scaleOverride?: any }
    | { type: 'retarget_pro_report'; packId?: string }
    | { type: 'reverb_zone_create'; zoneId: string; name: string; min: Record<string, any>; max: Record<string, any>; wet?: number; duration?: number; decay?: number }
    | { type: 'reverb_zone_remove'; zoneId: string }
    | { type: 'run_script'; commands: any[] }
    | { type: 'save_game'; slot: string }
    | { type: 'save_scene'; name?: string }
    | { type: 'save_state_snapshot'; name: string }
    | { type: 'scatter'; blueprint: Record<string, any>; count: number; center: Record<string, any>; radius: number; seed?: number }
    | { type: 'scene_diff'; beforeEntities?: any; afterEntities?: any }
    | { type: 'screen_flash'; color?: string; intensity?: number; duration?: number; mode?: string }
    | { type: 'screenshot'; filename?: any; width?: number; height?: number }
    | { type: 'selection_add'; entityId: number | string | Record<string, any> }
    | { type: 'selection_clear' }
    | { type: 'selection_get' }
    | { type: 'selection_set'; entityIds: any[]; primary?: any }
    | { type: 'selection_toggle'; entityId: number | string | Record<string, any> }
    | { type: 'sensorium_baseline'; name: string }
    | { type: 'sensorium_run'; script: any }
    | { type: 'sensorium_status' }
    | { type: 'sensorium_stop' }
    | { type: 'sensorium_test'; profile: any; options?: Record<string, any> }
    | { type: 'session_add_score'; amount?: number }
    | { type: 'session_finish'; result?: string }
    | { type: 'session_start' }
    | { type: 'set_angular_velocity'; entityId: number | string | Record<string, any>; x: number; y: number; z: number }
    | { type: 'set_bus_volume'; bus: any; volume: number }
    | { type: 'set_camera'; position: Record<string, any>; lookAt?: any; fov?: number }
    | { type: 'set_ccd'; entityId: number | string | Record<string, any>; enabled: boolean }
    | { type: 'set_debug_draw'; enabled: boolean }
    | { type: 'set_entity_name'; entityId: number | string | Record<string, any>; name: string }
    | { type: 'set_environment'; hdri?: any; sky?: any; background?: string; environmentIntensity?: any; backgroundIntensity?: any; backgroundBlurriness?: any }
    | { type: 'set_exposure'; value: any }
    | { type: 'set_gizmo_mode'; mode: string }
    | { type: 'set_gravity'; gravity: number }
    | { type: 'set_grid'; size?: any; divisions?: any; colorCenterLine?: any; colorGrid?: any; visible?: boolean }
    | { type: 'set_master_volume'; volume: number }
    | { type: 'set_material'; entityId: number | string | Record<string, any>; color?: string; roughness?: number; metalness?: number; emissive?: string; emissiveIntensity?: any; transparent?: any; opacity?: number }
    | { type: 'set_mode'; mode: string }
    | { type: 'set_nav_behavior_tree'; entityId: number | string | Record<string, any>; tree: Record<string, any> }
    | { type: 'set_nav_blackboard'; entityId: number | string | Record<string, any>; key: string; value: any }
    | { type: 'set_nav_steering'; entityId: number | string | Record<string, any>; steering: Record<string, any> }
    | { type: 'set_nav_target'; entityId: number | string | Record<string, any>; mode: string; targetX?: any; targetY?: any; targetZ?: any; targetEntityId?: number | string | Record<string, any>; patrol?: any }
    | { type: 'set_post_fx'; bloom?: any; bloomStrength?: any; outline?: any; vignette?: any; colorGrade?: any; chromaticAberration?: any; filmGrain?: any; godRays?: any; godRaysStrength?: any; godRaysDensity?: any; dof?: any; dofFocusDistance?: any; dofBokehScale?: any; dofAutoFocus?: any; ssr?: any; ssrIntensity?: any; ssrMaxDistance?: any; ssrThickness?: any; ssrFresnel?: any; volumetricFog?: any; fogDensity?: any; fogColor?: any; fogColorSun?: any; fogHeight?: any; fogHeightFalloff?: any; fogScattering?: any; fogAnisotropy?: any; fogMaxDistance?: any; motionBlur?: any; motionBlurIntensity?: any; motionBlurMax?: any; contactShadows?: any; contactShadowIntensity?: any; contactShadowDistance?: any; autoExposure?: any; exposureKey?: any; exposureMin?: any; exposureMax?: any; exposureSpeed?: any; taa?: any; taaFeedback?: any }
    | { type: 'set_shadow_strategy'; strategy: string }
    | { type: 'set_sky_environment'; elevationDeg?: number; azimuthDeg?: number; fogDensity?: any; fogColor?: any }
    | { type: 'set_snap'; enabled?: boolean; translateSnap?: any; rotateSnap?: any }
    | { type: 'set_state'; key: string; value: any }
    | { type: 'set_time_of_day'; hour: number }
    | { type: 'set_time_scale'; scale: number }
    | { type: 'set_tone'; exposure: any }
    | { type: 'set_transform'; entityId: number | string | Record<string, any>; position?: Record<string, any>; rotation?: Record<string, any>; scale?: Record<string, any> }
    | { type: 'set_vehicle_input'; entityId: number | string | Record<string, any>; throttle?: number; brake?: number; steer?: number; handbrake?: number }
    | { type: 'set_velocity'; entityId: number | string | Record<string, any>; x: number; y: number; z: number }
    | { type: 'set_visual_style'; style: string; overrides?: Record<string, any> }
    | { type: 'set_weather'; fogDensity?: any; fogColor?: any; ambient?: any }
    | { type: 'set_weather_preset'; kind: string; intensity?: number }
    | { type: 'spawn_decal'; ox: number; oy: number; oz: number; dx: number; dy: number; dz: number; size?: any; color?: string; lifetime?: any; tag?: string }
    | { type: 'spawn_entity'; x: number; y: number; z: number; glbPath: string }
    | { type: 'spawn_group'; blueprint: Record<string, any>; positions: any[] }
    | { type: 'spawn_smart'; query: string; x: number; y: number; z: number; dynamic?: boolean; scale?: number; compound?: boolean }
    | { type: 'spawn_trail'; color?: string; lifetime?: any; width?: number; segments?: any }
    | { type: 'spawn_vfx'; preset: string; x: number; y: number; z: number; duration?: number; loop?: boolean; maxParticles?: any }
    | { type: 'spawner_clear'; id: string }
    | { type: 'spawner_create'; def: Record<string, any> }
    | { type: 'spawner_remove'; id: string }
    | { type: 'spawner_start'; id: string }
    | { type: 'spawner_status'; id?: string }
    | { type: 'spawner_stop'; id: string }
    | { type: 'spring_bone_add'; entityId: number | string | Record<string, any>; bones: any[]; stiffness?: number; damping?: number; inertia?: number; radius?: number; gravity?: number }
    | { type: 'spring_bone_capsule'; entityId: number | string | Record<string, any>; startBone: any; endBone: any; radius: number }
    | { type: 'spring_bone_collider'; entityId: number | string | Record<string, any>; bone?: any; radius: number; offset?: any }
    | { type: 'spring_bone_remove'; entityId: number | string | Record<string, any> }
    | { type: 'stop_music'; fadeOut?: any }
    | { type: 'stop_sound'; src?: string; entityId?: number | string | Record<string, any> }
    | { type: 'tag_entity'; entityId: number | string | Record<string, any>; tag: string }
    | { type: 'target_lock_toggle' }
    | { type: 'terrain_create'; x: number; y: number; z: number; size?: any; resolution?: any; materialId?: any; seed?: number; baseNoiseAmplitude?: any }
    | { type: 'terrain_erode'; entityId?: number | string | Record<string, any>; kind: string; x?: number; z?: number; radius?: number; iterations?: number; options?: Record<string, any> }
    | { type: 'terrain_lod'; entityId?: number | string | Record<string, any>; distances?: any[] }
    | { type: 'terrain_material_layers'; entityId?: number | string | Record<string, any>; layers: any[] }
    | { type: 'terrain_noise'; entityId?: number | string | Record<string, any>; x: number; z: number; radius: number; amplitude: number; frequency?: number; octaves?: number; seed?: number; hardness?: number }
    | { type: 'terrain_paint'; entityId?: number | string | Record<string, any>; layer: string; x: number; z: number; radius: number; strength?: number; hardness?: number }
    | { type: 'terrain_ramp'; entityId?: number | string | Record<string, any>; from: string; to: string; width: number; hardness?: number }
    | { type: 'terrain_reset'; entityId?: number | string | Record<string, any> }
    | { type: 'terrain_sample'; entityId?: number | string | Record<string, any>; x: number; z: number }
    | { type: 'terrain_scatter'; entityId?: number | string | Record<string, any>; enabled?: boolean; density?: any; regenerate?: any }
    | { type: 'terrain_sculpt'; entityId?: number | string | Record<string, any>; op: string; x: number; z: number; radius: number; strength?: number; hardness?: number; targetHeight?: any; terraceStep?: any }
    | { type: 'terrain_spline'; entityId?: number | string | Record<string, any>; points: any[]; width: number; hardness?: number }
    | { type: 'timeline_create'; id: string; duration: number; loop?: boolean; tracks: Record<string, any> }
    | { type: 'timeline_play'; id: string; loop?: boolean }
    | { type: 'timeline_scrub'; id: string; time: number }
    | { type: 'timeline_stop'; id: string }
    | { type: 'tween_audio'; trackId?: any; volume: number; duration?: number; ease?: any }
    | { type: 'tween_camera'; x?: number; y?: number; z?: number; fov?: number; lookAt?: any; duration?: number; ease?: any }
    | { type: 'tween_cancel'; id?: string; entityId?: number | string | Record<string, any> }
    | { type: 'tween_color'; entityId?: number | string | Record<string, any>; property?: string; color: string; duration?: number; ease?: any }
    | { type: 'tween_complete'; id?: string }
    | { type: 'tween_effect_create'; steps: any[]; effectId?: string; autoPlay?: boolean }
    | { type: 'tween_from'; property: string; from: string; entityId?: number | string | Record<string, any>; target?: string; duration?: number; delay?: any; ease?: any; loops?: any; loopType?: any; conflictPolicy?: any; id?: string }
    | { type: 'tween_from_to'; property: string; from: string; to: string; entityId?: number | string | Record<string, any>; target?: string; duration?: number; delay?: any; ease?: any; loops?: any; loopType?: any; conflictPolicy?: any; id?: string }
    | { type: 'tween_inspect' }
    | { type: 'tween_material'; entityId: number | string | Record<string, any>; opacity?: number; roughness?: number; metalness?: number; emissive?: string; emissiveIntensity?: any; duration?: number; ease?: any }
    | { type: 'tween_move'; entityId: number | string | Record<string, any>; x?: number; y?: number; z?: number; duration?: number; ease?: any; loops?: any; loopType?: any; conflictPolicy?: any; id?: string }
    | { type: 'tween_path'; entityId: number | string | Record<string, any>; waypoints: any[]; duration?: number; ease?: any; lookAhead?: any; autoRotate?: any }
    | { type: 'tween_pause'; id?: string }
    | { type: 'tween_punch'; entityId: number | string | Record<string, any>; property?: string; x?: number; y?: number; z?: number; duration?: number; vibrato?: any; elasticity?: any }
    | { type: 'tween_resume'; id?: string }
    | { type: 'tween_reverse'; id: string }
    | { type: 'tween_rotate'; entityId: number | string | Record<string, any>; x?: number; y?: number; z?: number; duration?: number; ease?: any; loops?: any; loopType?: any; conflictPolicy?: any; id?: string }
    | { type: 'tween_scale'; entityId: number | string | Record<string, any>; scale?: number; x?: number; y?: number; z?: number; duration?: number; ease?: any; loops?: any; loopType?: any; conflictPolicy?: any; id?: string }
    | { type: 'tween_seek'; id: string; time?: number; progress?: number }
    | { type: 'tween_sequence_append'; sequenceId: string; op: string; entityId?: number | string | Record<string, any>; x?: number; y?: number; z?: number; scale?: number; duration?: number; ease?: any }
    | { type: 'tween_sequence_create'; sequenceId?: string; timeScale?: any; loops?: any; loopType?: any; autoPlay?: boolean }
    | { type: 'tween_sequence_join'; sequenceId: string; op: string; entityId?: number | string | Record<string, any>; x?: number; y?: number; z?: number; scale?: number; duration?: number; ease?: any }
    | { type: 'tween_sequence_marker'; sequenceId: string; name: string; time?: number }
    | { type: 'tween_sequence_play'; sequenceId: string }
    | { type: 'tween_shake'; entityId: number | string | Record<string, any>; property?: string; x?: number; y?: number; z?: number; duration?: number; frequency?: number; fadeOut?: any }
    | { type: 'tween_to'; property: string; to: string; entityId?: number | string | Record<string, any>; target?: string; duration?: number; delay?: any; ease?: any; loops?: any; loopType?: any; conflictPolicy?: any; id?: string }
    | { type: 'tween_validate'; sequenceJson: any }
    | { type: 'undo' }
    | { type: 'vehicle_status'; entityId?: number | string | Record<string, any> }
    | { type: 'viewport_detach' }
    | { type: 'viewport_reattach' }
    | { type: 'water_create'; kind?: string; seaLevel?: number; size?: any; segments?: any; position?: Record<string, any>; waveScale?: number; choppiness?: number; foam?: number; opacity?: number; deepColor?: string; shallowColor?: string; foamColor?: string }
    | { type: 'water_remove' }
    | { type: 'water_sample'; x: number; z: number }
    | { type: 'water_set'; seaLevel?: number; waveScale?: number; choppiness?: number; foam?: number; opacity?: number; deepColor?: string; shallowColor?: string; foamColor?: string }
    | { type: 'weather_set'; state: string; transitionDuration?: any }
    | { type: 'wind_set'; dirX?: number; dirZ?: number; strength?: number; gustiness?: number }
    | { type: 'world_canvas_create'; canvasId: string; width?: number; height?: number; billboard?: any; position?: Record<string, any>; text?: string }
    | { type: 'world_canvas_destroy'; canvasId: string }
    | { type: 'world_canvas_set_text'; canvasId: string; text: string; color?: string; background?: string }
    | { type: 'world_compose'; entityId?: number | string | Record<string, any>; seed?: number; theme?: any; landform?: any; mood?: any; quality?: any; size?: any; resolution?: any; center?: Record<string, any>; water?: any; foliage?: any; navigation?: any; autoLayout?: any; paths?: any; pointsOfInterest?: any }
    | { type: 'world_generate'; entityId?: number | string | Record<string, any>; seed?: number; size?: any; resolution?: any; amplitude?: number; oceanDepthRatio?: number; continentScale?: number; landBias?: number; mountainScale?: number; mountainAmount?: number; hillScale?: number; detailScale?: number; moistureScale?: number; warp?: number; island?: boolean; islandFalloff?: number; climate?: any }
    | { type: 'world_report' }
    | { type: 'zoom_in'; factor?: any }
    | { type: 'zoom_out'; factor?: any }
    | { type: 'zoom_reset' }
}
