import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const ONEDRIVE_PATH = 'C:\\Users\\Jetma\\OneDrive\\Documents\\MIXAMO ANIMATIONS-20260620T021754Z-3-001\\MIXAMO ANIMATIONS';
const PROJECT_ROOT = path.resolve(__dirname, '..');
const PUBLIC_MIXAMO_DIR = path.join(PROJECT_ROOT, 'public', 'assets', 'mixamo');

console.log('Starting Mixamo Asset Import...');
console.log('Source:', ONEDRIVE_PATH);
console.log('Destination:', PUBLIC_MIXAMO_DIR);

if (!fs.existsSync(ONEDRIVE_PATH)) {
  console.error(`Error: Source directory '${ONEDRIVE_PATH}' does not exist.`);
  process.exit(1);
}

// Ensure destination directories
fs.mkdirSync(path.join(PUBLIC_MIXAMO_DIR, 'characters'), { recursive: true });
fs.mkdirSync(path.join(PUBLIC_MIXAMO_DIR, 'animations'), { recursive: true });

const manifest = {
  characters: [],
  animations: {}
};

function copyFilesRecursively(src, destSubDir, category) {
  if (!fs.existsSync(src)) return;
  const entries = fs.readdirSync(src, { withFileTypes: true });

  for (const entry of entries) {
    const srcPath = path.join(src, entry.name);
    if (entry.isDirectory()) {
      copyFilesRecursively(srcPath, path.join(destSubDir, entry.name), category);
    } else if (entry.isFile() && entry.name.toLowerCase().endsWith('.glb')) {
      // Create destination directory if not exists
      const fullDestDir = path.join(PUBLIC_MIXAMO_DIR, destSubDir);
      fs.mkdirSync(fullDestDir, { recursive: true });

      const destPath = path.join(fullDestDir, entry.name);
      fs.copyFileSync(srcPath, destPath);

      // Relative path for Web loading (using forward slashes)
      const webPath = `/assets/mixamo/${destSubDir}/${entry.name}`.replace(/\\/g, '/');
      const id = path.parse(entry.name).name;

      if (category === 'characters') {
        manifest.characters.push({ id, path: webPath });
        console.log(`Copied character: ${id} -> ${webPath}`);
      } else {
        if (!manifest.animations[category]) {
          manifest.animations[category] = [];
        }
        manifest.animations[category].push({ id, path: webPath });
        console.log(`Copied animation [${category}]: ${id} -> ${webPath}`);
      }
    }
  }
}

// Copy characters
copyFilesRecursively(path.join(ONEDRIVE_PATH, 'CHAREACTERS'), 'characters', 'characters');

// Copy animations from subfolders
const animFolders = [
  'Locomotion',
  'Attack Melee',
  'Attack ranged',
  'Blocking',
  'DYING',
  'Specials',
  'blocks',
  'flight',
  'swords animations'
];

for (const folder of animFolders) {
  copyFilesRecursively(path.join(ONEDRIVE_PATH, folder), `animations/${folder}`, folder);
}

// Generate the TypeScript file
const tsPath = path.join(PROJECT_ROOT, 'src', 'animation', 'MixamoPresets.ts');
const tsContent = `// Automatically generated by scripts/import-mixamo.js. Do not edit directly.

export interface MixamoCharacterPreset {
  id: string;
  path: string;
}

export interface MixamoAnimationPreset {
  id: string;
  path: string;
}

export const MIXAMO_CHARACTERS: MixamoCharacterPreset[] = ${JSON.stringify(manifest.characters, null, 2)};

export const MIXAMO_ANIMATIONS: Record<string, MixamoAnimationPreset[]> = ${JSON.stringify(manifest.animations, null, 2)};
`;

fs.writeFileSync(tsPath, tsContent);
console.log(`Wrote presets manifest to ${tsPath}`);
console.log('Import completed successfully!');
