// Automatically generated by scripts/import-mixamo.js. Do not edit directly.

export interface MixamoCharacterPreset {
  id: string;
  path: string;
}

export interface MixamoAnimationPreset {
  id: string;
  path: string;
}

export const MIXAMO_CHARACTERS: MixamoCharacterPreset[] = [
  {
    "id": "ayo",
    "path": "/assets/mixamo/characters/ayo.glb"
  },
  {
    "id": "hana",
    "path": "/assets/mixamo/characters/hana.glb"
  },
  {
    "id": "opp",
    "path": "/assets/mixamo/characters/opp.glb"
  },
  {
    "id": "RAYNEFBX",
    "path": "/assets/mixamo/characters/RAYNEFBX.glb"
  }
];

export const MIXAMO_ANIMATIONS: Record<string, MixamoAnimationPreset[]> = {
  "Locomotion": [
    {
      "id": "Backflip",
      "path": "/assets/mixamo/animations/Locomotion/Backflip.glb"
    },
    {
      "id": "Dodging Left(1)",
      "path": "/assets/mixamo/animations/Locomotion/Dodging Left(1).glb"
    },
    {
      "id": "Dodging Right",
      "path": "/assets/mixamo/animations/Locomotion/Dodging Right.glb"
    },
    {
      "id": "idle",
      "path": "/assets/mixamo/animations/Locomotion/idle.glb"
    },
    {
      "id": "jump",
      "path": "/assets/mixamo/animations/Locomotion/jump.glb"
    },
    {
      "id": "left strafe walking",
      "path": "/assets/mixamo/animations/Locomotion/left strafe walking.glb"
    },
    {
      "id": "left strafe",
      "path": "/assets/mixamo/animations/Locomotion/left strafe.glb"
    },
    {
      "id": "left turn 90",
      "path": "/assets/mixamo/animations/Locomotion/left turn 90.glb"
    },
    {
      "id": "left turn",
      "path": "/assets/mixamo/animations/Locomotion/left turn.glb"
    },
    {
      "id": "right strafe walking",
      "path": "/assets/mixamo/animations/Locomotion/right strafe walking.glb"
    },
    {
      "id": "right strafe",
      "path": "/assets/mixamo/animations/Locomotion/right strafe.glb"
    },
    {
      "id": "right turn 90",
      "path": "/assets/mixamo/animations/Locomotion/right turn 90.glb"
    },
    {
      "id": "right turn",
      "path": "/assets/mixamo/animations/Locomotion/right turn.glb"
    },
    {
      "id": "running",
      "path": "/assets/mixamo/animations/Locomotion/running.glb"
    },
    {
      "id": "Walking",
      "path": "/assets/mixamo/animations/Locomotion/Walking.glb"
    }
  ],
  "Attack Melee": [
    {
      "id": "Great Sword Slash",
      "path": "/assets/mixamo/animations/Attack Melee/Great Sword Slash.glb"
    },
    {
      "id": "Hook Punch",
      "path": "/assets/mixamo/animations/Attack Melee/Hook Punch.glb"
    },
    {
      "id": "Hurricane Kick",
      "path": "/assets/mixamo/animations/Attack Melee/Hurricane Kick.glb"
    },
    {
      "id": "Idle",
      "path": "/assets/mixamo/animations/Attack Melee/Idle.glb"
    },
    {
      "id": "Kicking",
      "path": "/assets/mixamo/animations/Attack Melee/Kicking.glb"
    },
    {
      "id": "Mma Kick",
      "path": "/assets/mixamo/animations/Attack Melee/Mma Kick.glb"
    },
    {
      "id": "Punch To Elbow Combo",
      "path": "/assets/mixamo/animations/Attack Melee/Punch To Elbow Combo.glb"
    },
    {
      "id": "Quad Punch",
      "path": "/assets/mixamo/animations/Attack Melee/Quad Punch.glb"
    },
    {
      "id": "sword_draw",
      "path": "/assets/mixamo/animations/Attack Melee/sword_draw.glb"
    },
    {
      "id": "sword_sheathe",
      "path": "/assets/mixamo/animations/Attack Melee/sword_sheathe.glb"
    },
    {
      "id": "Uppercut Jab",
      "path": "/assets/mixamo/animations/Attack Melee/Uppercut Jab.glb"
    }
  ],
  "Attack ranged": [
    {
      "id": "Fireball",
      "path": "/assets/mixamo/animations/Attack ranged/Fireball.glb"
    }
  ],
  "Blocking": [
    {
      "id": "Dodging Left(1)",
      "path": "/assets/mixamo/animations/Blocking/Dodging Left(1).glb"
    },
    {
      "id": "Dodging Right",
      "path": "/assets/mixamo/animations/Blocking/Dodging Right.glb"
    },
    {
      "id": "Inward Block",
      "path": "/assets/mixamo/animations/Blocking/Inward Block.glb"
    },
    {
      "id": "jump",
      "path": "/assets/mixamo/animations/Blocking/jump.glb"
    },
    {
      "id": "Standing Block Idle",
      "path": "/assets/mixamo/animations/Blocking/Standing Block Idle.glb"
    }
  ],
  "DYING": [
    {
      "id": "Dying (1)",
      "path": "/assets/mixamo/animations/DYING/Dying (1).glb"
    },
    {
      "id": "Dying (2)",
      "path": "/assets/mixamo/animations/DYING/Dying (2).glb"
    },
    {
      "id": "Dying",
      "path": "/assets/mixamo/animations/DYING/Dying.glb"
    }
  ],
  "Specials": [
    {
      "id": "aura boomerang",
      "path": "/assets/mixamo/animations/Specials/aura boomerang.glb"
    },
    {
      "id": "Casting Spell",
      "path": "/assets/mixamo/animations/Specials/Casting Spell.glb"
    },
    {
      "id": "Magic Heal",
      "path": "/assets/mixamo/animations/Specials/Magic Heal.glb"
    },
    {
      "id": "Magic Spell Casting",
      "path": "/assets/mixamo/animations/Specials/Magic Spell Casting.glb"
    },
    {
      "id": "SpecialMove_004_00_All_VFX",
      "path": "/assets/mixamo/animations/Specials/SpecialMove_004_00_All_VFX.glb"
    },
    {
      "id": "Standing 2H Magic Attack 03",
      "path": "/assets/mixamo/animations/Specials/Standing 2H Magic Attack 03.glb"
    },
    {
      "id": "Two Hand Spell Casting",
      "path": "/assets/mixamo/animations/Specials/Two Hand Spell Casting.glb"
    }
  ],
  "blocks": [
    {
      "id": "Inward Block",
      "path": "/assets/mixamo/animations/blocks/Inward Block.glb"
    },
    {
      "id": "Standing Block Idle",
      "path": "/assets/mixamo/animations/blocks/Standing Block Idle.glb"
    }
  ],
  "flight": [
    {
      "id": "Flying",
      "path": "/assets/mixamo/animations/flight/Flying.glb"
    }
  ],
  "swords animations": [
    {
      "id": "Great Sword Strafe",
      "path": "/assets/mixamo/animations/swords animations/Great Sword Strafe.glb"
    },
    {
      "id": "Great Sword Walk",
      "path": "/assets/mixamo/animations/swords animations/Great Sword Walk.glb"
    },
    {
      "id": "Run With Sword",
      "path": "/assets/mixamo/animations/swords animations/Run With Sword.glb"
    },
    {
      "id": "Sheathing Sword",
      "path": "/assets/mixamo/animations/swords animations/Sheathing Sword.glb"
    },
    {
      "id": "Spell cast with Sword",
      "path": "/assets/mixamo/animations/swords animations/Spell cast with Sword.glb"
    },
    {
      "id": "casting spell with one hand sword in the other hand",
      "path": "/assets/mixamo/animations/swords animations/sword locomotion/casting spell with one hand sword in the other hand.glb"
    },
    {
      "id": "Great Sword Strafe",
      "path": "/assets/mixamo/animations/swords animations/sword locomotion/Great Sword Strafe.glb"
    },
    {
      "id": "Great Sword Walk",
      "path": "/assets/mixamo/animations/swords animations/sword locomotion/Great Sword Walk.glb"
    },
    {
      "id": "Run With Sword",
      "path": "/assets/mixamo/animations/swords animations/sword locomotion/Run With Sword.glb"
    },
    {
      "id": "Sheathing Sword",
      "path": "/assets/mixamo/animations/swords animations/sword locomotion/Sheathing Sword.glb"
    },
    {
      "id": "Two Handed Sword Death",
      "path": "/assets/mixamo/animations/swords animations/sword locomotion/Two Handed Sword Death.glb"
    },
    {
      "id": "Withdrawing Sword",
      "path": "/assets/mixamo/animations/swords animations/sword locomotion/Withdrawing Sword.glb"
    },
    {
      "id": "Great Sword Jump Attack",
      "path": "/assets/mixamo/animations/swords animations/sword melee/Great Sword Jump Attack.glb"
    },
    {
      "id": "Great Sword Slash",
      "path": "/assets/mixamo/animations/swords animations/sword melee/Great Sword Slash.glb"
    },
    {
      "id": "Stable Sword In Slash",
      "path": "/assets/mixamo/animations/swords animations/sword melee/Stable Sword In Slash.glb"
    },
    {
      "id": "Stable Sword Out Slash",
      "path": "/assets/mixamo/animations/swords animations/sword melee/Stable Sword Out Slash.glb"
    },
    {
      "id": "Great Sword Slash Whilrwind",
      "path": "/assets/mixamo/animations/swords animations/sword ranged/Great Sword Slash Whilrwind.glb"
    },
    {
      "id": "Stable Sword Inward Slash",
      "path": "/assets/mixamo/animations/swords animations/sword ranged/Stable Sword Inward Slash.glb"
    },
    {
      "id": "Stable Sword Outward ShockwaveSlash",
      "path": "/assets/mixamo/animations/swords animations/sword ranged/Stable Sword Outward ShockwaveSlash.glb"
    },
    {
      "id": "Two Handed Sword Death",
      "path": "/assets/mixamo/animations/swords animations/Two Handed Sword Death.glb"
    },
    {
      "id": "Withdrawing Sword",
      "path": "/assets/mixamo/animations/swords animations/Withdrawing Sword.glb"
    }
  ]
};
