import type { SceneManager, EntityId } from '../../ecs/SceneManager';
import type { WorldOrigin } from '../../streaming/WorldOrigin';
import type { InputManager } from '../../engine/InputManager';
import type { AssetManifest } from '../../animation/AssetManifest';
import type { SemanticAssetRegistry } from '../../assets/SemanticAssetRegistry';
import type { Viewport } from '../../rendering/Viewport';
import type { PhysicsWorld } from '../../physics/PhysicsWorld';
import type { CinematicCamera } from '../../cinematic/CinematicCamera';
import type { CutsceneDirector } from '../../cinematic/CutsceneDirector';
import type { AudioManager } from '../../audio/AudioManager';
import type { SensoriumRunner } from '../../sensorium';
import type { ChunkManager } from '../../streaming/ChunkManager';
import type { NavigationSystem } from '../NavigationSystem';
import type { CullingSystem } from '../../rendering/CullingSystem';
import type { VehicleSystem } from '../../physics/VehicleSystem';
import type { LODSystem } from '../../rendering/LODSystem';
import type { CombatSystem } from '../../ecs/CombatSystem';
import type { RuntimeAssetImporter } from '../../streaming/RuntimeAssetImporter';
import type { TerrainSystem } from '../../terrain/TerrainSystem';
import type { DayNightCycle } from '../../rendering/DayNightCycle';
import type { WaterSystem } from '../../water/WaterSystem';
import type { CloudLayer } from '../../rendering/CloudLayer';
import type { WindSystem } from '../../world/WindSystem';
import type { FoliageSystem } from '../../world/FoliageSystem';
import type { DebugDraw } from '../../rendering/DebugDraw';
import type { HUD } from '../../ui/HUD';
import type { InputReplay } from '../../playback/InputReplay';
import type { DialogueSystem } from '../../ui/DialogueSystem';
import type { GameplayDirector } from '../../gameplay';
import type { InventorySystem } from '../../items';
import type { InteractionSystem } from '../../interaction';
import type { SpawnerSystem } from '../../spawning';
import type { SaveSystem } from '../../persistence';
import type { BakeRegistry } from '../../features/BakeRegistry';
import type { EffectsController } from '../../effects/EffectsController';
import type { VfxPresetName } from '../../vfx/ParticleEmitter';
import type { AICommand } from '../AIBridge';
import type { AnimationPackRegistry } from '../../animation/AnimationPackRegistry';
import type { AnimationImporter } from '../../animation/AnimationImporter';
import type { AnimationStateMachine } from '../../animation/AnimationStateMachine';
import * as THREE from 'three';

export type CommandHandler = (cmd: any) => unknown;
export type CommandMap = Map<string, CommandHandler>;

export interface PathFollower {
  entityId: EntityId;
  path: {
    sampleUniform: (t: number, out: THREE.Vector3) => THREE.Vector3;
    tangentUniform: (t: number, out: THREE.Vector3) => THREE.Vector3;
    length: number;
    closed: boolean;
  };
  speed: number;
  t: number;
  loop: boolean;
  lookAlongPath: boolean;
}

export interface CmdCtx {
  sceneManager: SceneManager;
  worldOrigin: WorldOrigin;
  input: InputManager;
  manifest: AssetManifest;
  assets?: SemanticAssetRegistry;
  viewport: Viewport;
  physicsWorld: PhysicsWorld;
  cinematic: CinematicCamera;
  cutsceneDirector?: CutsceneDirector;
  audio: AudioManager;
  sensorium: SensoriumRunner;
  chunkManager?: ChunkManager;
  effects?: EffectsController;
  nav?: NavigationSystem;
  culling?: CullingSystem;
  vehicles?: VehicleSystem;
  lod?: LODSystem;
  combat?: CombatSystem;
  assetImporter?: RuntimeAssetImporter;
  terrain?: TerrainSystem;
  dayNight?: DayNightCycle;
  water?: WaterSystem;
  clouds?: CloudLayer;
  wind?: WindSystem;
  foliage?: FoliageSystem;
  debugDraw?: DebugDraw;
  hud?: HUD;
  replay?: InputReplay;
  dialogueSystem?: DialogueSystem;
  gameplay?: GameplayDirector;
  items?: InventorySystem;
  interaction?: InteractionSystem;
  spawner?: SpawnerSystem;
  saves?: SaveSystem;
  bakes?: BakeRegistry;
  animRegistry?: AnimationPackRegistry;
  animImporter?: AnimationImporter;
  findAsm?: (entityId: number) => AnimationStateMachine | null;
  getAllAsm?: () => Iterable<AnimationStateMachine>;
  getSelectedEntityId?: () => number | null;
  motionDirector?: import('../../motion').MotionDirectorManager;
  inspectorStudio?: import('../../inspector').InspectorStudioManager;
  tweenDirector?: import('../../tween').TweenDirectorManager;
  jointSystem?: import('../../physics/JointSystem').JointSystem;
  ragdollBuilder?: import('../../physics/RagdollBuilder').RagdollBuilder;
  getLocomotor?: (entityId: number) => import('../../character/CharacterLocomotor').CharacterLocomotor | undefined;
  history?: import('../../authoring/CommandHistory').CommandHistory;
  morphSystem?: import('../../animation/MorphTargetSystem').MorphTargetSystem;
  animEventBridge?: import('../../animation/StateMachineEventBridge').StateMachineEventBridge;
  getAimIKSolver?: (entityId: number) => import('../../animation/AimIKSolver').AimIKSolver | undefined;
  setAimIKTarget?: (entityId: number, worldTarget: THREE.Vector3, weight: number) => boolean;
  reverbSystem?: import('../../audio/ReverbZoneSystem').ReverbZoneSystem;
  timelineSequencer?: import('../../cinematic/TimelineSequencer').TimelineSequencer;
  volumetricFog?: import('../../rendering/VolumetricFogSystem').VolumetricFogSystem;
  decalSystem?: import('../../rendering/DecalSystem').DecalSystem;
  meshFracturer?: import('../../physics/MeshFracturer').MeshFracturer;
  weatherSystem?: import('../../environment/WeatherSystem').WeatherSystem;
  aiDirector?: import('../AIDirector').AIDirector;
  clothSystem?: import('../../physics/VerletClothSystem').VerletClothSystem;
  createReflectionProbe?: (id: string, position: THREE.Vector3, config?: import('../../rendering/ReflectionProbe').ReflectionProbeConfig) => boolean;
  removeReflectionProbe?: (id: string) => boolean;
  markReflectionProbeDirty?: (id: string) => boolean;
  springBones?: import('../../physics/SpringBoneSystem').SpringBoneSystem;
  activeRagdolls?: import('../../physics/ActiveRagdollSystem').ActiveRagdollSystem;
  footIK?: import('../../animation/FootIKSystem').FootIKSystem;
  buoyancy?: import('../../physics/BuoyancySystem').BuoyancySystem;
  chunkDeltas?: import('../../streaming/ChunkDeltaBinder').ChunkDeltaBinder;
  hlod?: import('../../rendering/HlodSystem').HlodSystem;
  network?: import('../../network/NetworkSystem').NetworkSystem;
  gpuParticles?: import('../../vfx/GpuParticleSystem').GpuParticleSystem;
  prefabs?: import('../../engine/PrefabManager').PrefabManager;
  profiler?: import('../../diagnostics/FrameProfiler').FrameProfiler;
  qualityScaler?: import('../../rendering/QualityScaler').QualityScaler;
  assetCache?: import('../../animation/AssetCache').AssetCache;
  selection?: import('../../editor/SelectionManager').SelectionManager;
  selectionChanged?: () => void;
  gameplayFeatures?: import('../../features/gameplay/GameplayFeatureManager').GameplayFeatureManager;

  spawnVfx: (preset: VfxPresetName, worldPos: THREE.Vector3, opts: { duration?: number; loop?: boolean; maxParticles?: number }) => void;
  burstVfx: (preset: VfxPresetName, worldPos: THREE.Vector3, count: number) => void;
  captureScreenshot: (filename: string, width?: number, height?: number) => Promise<void>;
  setTimeOfDay: (hour: number) => void;
  zoomIn?: (factor?: number) => void;
  zoomOut?: (factor?: number) => void;
  zoomReset?: () => void;
  frameAll?: (padding?: number) => void;
  frameEntity?: (entityId: EntityId, padding?: number) => void;
  applyCameraPreset?: (id: string, opts?: { anchorToSelection?: boolean }) => boolean;
  cycleCameraPreset?: (dir: 1 | -1) => string | null;
  listCameraPresets?: () => import('../../cinematic/CameraPresets').CameraPreset[];
  markDynamicLightsDirty?: () => void;

  entityNames: Map<EntityId, string>;
  followers: PathFollower[];
  setQueryResult: (val: unknown) => void;
  trackAsync: <T>(p: Promise<T>) => Promise<T>;
  execute: (cmd: AICommand) => void;
  resolveEntity: (ref: string) => EntityId | undefined;
  getEntityTags: (id: EntityId) => string[];
  setSensoriumReport: (r: unknown) => void;

  _setSnap?: (enabled?: boolean, translateSnap?: number, rotateSnap?: number) => void;
  _setGrid?: (config: any) => void;
  _setGizmoMode?: (mode: 'translate' | 'rotate' | 'scale') => void;
  _detachViewport?: () => void;
  _reattachViewport?: () => void;

  _engPos: THREE.Vector3;
  _worldPos: THREE.Vector3;
  _quat: THREE.Quaternion;
  _v: THREE.Vector3;
}
